create sequence hibernate_sequence start 1 increment 1;
create table batman_user (id int8 not null, primary key (id));
create table discipline (id int8 not null, discipline_type int4, field_type int4, division_name varchar(255), primary key (id));
create table division (name varchar(255) not null, primary key (name));
create table player (id int8 not null, club varchar(255), first_name varchar(255), gender int4, last_name varchar(255), primary key (id));
create table registration (id int8 not null, registration_date date, state int4, partner_id int8, tournament_discipline_id int8, user_id int8, primary key (id));
create table tournament (id int8 not null, close_of_entries date, end date, name varchar(255), start date, primary key (id));
create table tournament_discipline (id int8 not null, capacity int4, registration_fee float8, discipline_id int8, tournament_id int8, primary key (id));
alter table if exists discipline add constraint FKtq6u76woehchd6sntyacwaf9q foreign key (division_name) references division;
alter table if exists registration add constraint FKhmyyu2ljiwo8x10kjfab1pkru foreign key (partner_id) references player;
alter table if exists registration add constraint FKif3c0waonn41d3n17ci6j7erg foreign key (tournament_discipline_id) references tournament_discipline;
alter table if exists registration add constraint FKce4x4ppqh1v7iyicau6psp5j7 foreign key (user_id) references batman_user;
alter table if exists tournament_discipline add constraint FKmd3du7y64cywy8aea1l9terot foreign key (discipline_id) references discipline;
alter table if exists tournament_discipline add constraint FK4nqu9yp0852tly8yewyen1p2 foreign key (tournament_id) references tournament;
